### ISSUE TITLE
floats are too small

### ISSUE THREAD

**Issue by mfchung** [lbildzinkas/BitfinexApiSharp#1]
TickerRespose should be using decimals or doubles surely? a bitcoin has 100 million satoshis, thats already a 9 digit number.

**Comment by lbildzinkas** [comment]
I can see that, but I am only following their spec, actually, take a look: https://docs.bitfinex.com/v2/reference#ws-public-ticker

**Comment by mfchung** [comment]
yes.... but the spec is for javascript. a javascript float is actually a double

**Comment by lbildzinkas** [comment]
Interesting I wasn't aware of that, I will probably change to decimal then. Thanks!

**Comment by mfchung** [comment]
welcomed.

**Comment by lbildzinkas** [comment]
Issue solved.
